### ISSUE TITLE
DELETE layers, should delete ML stuff

### ISSUE THREAD

**Issue by schollz** [sjsafranek/findauth#4]

**Comment by sjsafranek** [comment]
DELETE /locations?group=X&names=Y,Z,W

**Comment by sjsafranek** [comment]
the following api call is run against the Find MachineLearning server. Since gis server doesnt know what locations are learned this is done in a "for" loop for each feature within the deleted layer. As a result the HTTP status is passed over unless it is above a 499. If a status code above 500 Find Auth raises an error and function ends. If Find MachineLearning location delete requests are "successful" a delete request is run against Find GIS to delete the layer. 

This workflow is to prevent a bad state where Find MachineLearning knows a location that Find GIS doesn't. 

DELETE /locations?group=X&names=Y
